import torch

N_EPOCHS = 10

IN_CHANNELS=40  
OUT_CHANNELS=IN_CHANNELS
KERNEL_SIZE=5
PADDING_TYPE="same"
STRIDE=1
ACTIVATION=torch.nn.ReLU()
DROPOUT_CNN=0.2
BATCH_NORM=True
P_ENCODER_GRU_HIDDEN_SIZE=64

P_MAX_LEN = 128
P_NUM_FEATURES = 64
P_GRU_INPUT_SIZE = 16

EMBEDDING_DIM = 64
NUM_EMBEDDINGS = 128