import torch

N_EPOCHS = 10

IN_CHANNELS=16
OUT_CHANNELS=IN_CHANNELS
KERNEL_SIZE=5
PADDING_TYPE="same"
STRIDE=1
ACTIVATION=torch.nn.ReLU()
DROPOUT_CNN=0.045
BATCH_NORM=True
MS_ENCODER_GRU_HIDDEN_SIZE=128

MS_MAX_LEN = 256
MS_NUM_FEATURES = 128
MS_GRU_INPUT_SIZE = 16